-- Migration: create OilLog table for fuel/oil log workflow managed by php/server/oillogs.php
-- Run this in the `project_noncon` schema before using the digital oil log UI.

CREATE TABLE IF NOT EXISTS `OilLog` (
  `OilLog_Id` INT NOT NULL AUTO_INCREMENT,
  `Center_Id` INT DEFAULT NULL,
  `Document_No` VARCHAR(50) DEFAULT NULL,
  `Document_Date` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `Shift` VARCHAR(20) DEFAULT NULL,
  `Work_Type` VARCHAR(30) DEFAULT NULL,
  `Work_Order` VARCHAR(100) DEFAULT NULL,
  `Project_Name` VARCHAR(255) DEFAULT NULL,
  `Location_Name` VARCHAR(255) DEFAULT NULL,
  `Requester_Name` VARCHAR(120) DEFAULT NULL,
  `Supervisor_Name` VARCHAR(120) DEFAULT NULL,
  `Machine_Code` VARCHAR(50) DEFAULT NULL,
  `Machine_Name` VARCHAR(120) DEFAULT NULL,
  `Machine_Description` VARCHAR(255) DEFAULT NULL,
  `Operation_Details` TEXT,
  `Fuel_Type` VARCHAR(50) NOT NULL,
  `Fuel_Amount_Liters` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `Fuel_Details_JSON` JSON DEFAULT NULL,
  `Photo_Attachments_JSON` JSON DEFAULT NULL,
  `Fuel_Ticket_No` VARCHAR(80) DEFAULT NULL,
  `Tank_Before_Liters` DECIMAL(10,2) DEFAULT NULL,
  `Tank_After_Liters` DECIMAL(10,2) DEFAULT NULL,
  `Meter_Hour_Start` DECIMAL(10,2) DEFAULT NULL,
  `Meter_Hour_End` DECIMAL(10,2) DEFAULT NULL,
  `Odometer_Start` DECIMAL(10,2) DEFAULT NULL,
  `Odometer_End` DECIMAL(10,2) DEFAULT NULL,
  `Work_Meter_Start` DECIMAL(10,2) DEFAULT NULL,
  `Work_Meter_End` DECIMAL(10,2) DEFAULT NULL,
  `Work_Meter_Total` DECIMAL(10,2) DEFAULT NULL,
  `Time_Morning_Start` TIME DEFAULT NULL,
  `Time_Morning_End` TIME DEFAULT NULL,
  `Time_Morning_Total` DECIMAL(6,2) DEFAULT NULL,
  `Time_Afternoon_Start` TIME DEFAULT NULL,
  `Time_Afternoon_End` TIME DEFAULT NULL,
  `Time_Afternoon_Total` DECIMAL(6,2) DEFAULT NULL,
  `Time_Ot_Start` TIME DEFAULT NULL,
  `Time_Ot_End` TIME DEFAULT NULL,
  `Time_Ot_Total` DECIMAL(6,2) DEFAULT NULL,
  `Fuel_Time` TIME DEFAULT NULL,
  `Operator_Name` VARCHAR(120) DEFAULT NULL,
  `Assistant_Name` VARCHAR(120) DEFAULT NULL,
  `Recorder_Name` VARCHAR(120) DEFAULT NULL,
  `Notes` TEXT,
  `Checklist_JSON` TEXT DEFAULT NULL,
  `Created_By` VARCHAR(120) DEFAULT NULL,
  `Created_At` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `Updated_At` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`OilLog_Id`),
  KEY `idx_oillog_center` (`Center_Id`),
  KEY `idx_oillog_document_date` (`Document_Date`),
  KEY `idx_oillog_fuel_type` (`Fuel_Type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
