SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS Center (
  Center_Id INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(28) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Address VARCHAR(255),
  CenterName VARCHAR(255),
  `Role` VARCHAR(128) NOT NULL DEFAULT 'operator',
  Created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated_at DATETIME NULL DEFAULT NULL,
  Last_seen DATETIME NULL DEFAULT NULL,
  Name VARCHAR(255) NOT NULL,
  Lastname VARCHAR(255) NOT NULL,
  Phone VARCHAR(32) NOT NULL,
  Employee_Id VARCHAR(20) NOT NULL,
  UNIQUE KEY uq_center_username (Username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Machines (
  Machine_Id INT AUTO_INCREMENT PRIMARY KEY,
  Machine_Type ENUM('Heavy','Support','Plant','Vehicle','Crane') DEFAULT NULL,
  Company_code VARCHAR(50),
  `Recipient` VARCHAR(255),
  Equipment VARCHAR(50),
  Description TEXT,
  `Status` VARCHAR(255),
  Specification TEXT,
  Chassis_Number VARCHAR(200),
  Engine_Serial_Number VARCHAR(200),
  Engine_Model VARCHAR(200),
  Engine_Power VARCHAR(10),
  Engine_Capacity VARCHAR(10),
  License_plate_Number VARCHAR(100),
  Tax DATE,
  Insurance DATE,
  Duties INT(10),
  Note TEXT,
  `Class` VARCHAR(20),
  Assest_Number VARCHAR(100),
  Manufacture VARCHAR(200),
  `Keyword` VARCHAR(255),
  Registered DATE,
  MCCreated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS DailyChecklistItem (
  Item_Id INT AUTO_INCREMENT PRIMARY KEY,
  Item_Order INT NOT NULL,
  Title VARCHAR(255) NOT NULL,
  Standard VARCHAR(255) NULL,
  Frequency VARCHAR(64) NULL,
  Is_Active BOOLEAN NOT NULL DEFAULT TRUE,
  Is_Signature BOOLEAN NOT NULL DEFAULT FALSE,
  Created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated_at DATETIME NULL DEFAULT NULL,
  UNIQUE KEY uq_item_order (Item_Order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS DailyForm (
  DailyForm_Id INT AUTO_INCREMENT PRIMARY KEY,
  Machine_Id INT NOT NULL,
  Center_Id INT NOT NULL,
  Form_Month INT NOT NULL,
  Form_Year INT NOT NULL,
  Start_Use_Date DATE NULL,
  Unit_Work VARCHAR(255) NULL,
  Problem_Description TEXT NULL,
  Overall_Status ENUM('ปกติ','ผิดปกติ','S','B','-') NOT NULL DEFAULT '-',
  DFCreated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated_at DATETIME NULL DEFAULT NULL,
  CONSTRAINT fk_dailyform_machine FOREIGN KEY (Machine_Id) REFERENCES Machines(Machine_Id) ON DELETE CASCADE,
  CONSTRAINT fk_dailyform_center FOREIGN KEY (Center_Id) REFERENCES Center(Center_Id) ON DELETE CASCADE,
  INDEX idx_dailyform_machine (Machine_Id),
  INDEX idx_dailyform_center (Center_Id),
  UNIQUE KEY uq_dailyform_machine_period_unit (Machine_Id, Form_Year, Form_Month, Unit_Work),
  INDEX idx_dailyform_machine_period (Machine_Id, Form_Year, Form_Month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS DailyChecklistValue (
  Value_Id INT AUTO_INCREMENT PRIMARY KEY,
  DailyForm_Id INT NOT NULL,
  Item_Id INT NOT NULL,
  Check_Day INT NOT NULL,
  Result ENUM('ปกติ','ผิดปกติ','S','B','-') NOT NULL DEFAULT '-',
  Note TEXT NULL,
  Signature VARCHAR(255) NULL,
  Checked_By VARCHAR(100) NULL,
  Checked_At DATETIME NULL,
  Created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated_at DATETIME NULL DEFAULT NULL,
  CONSTRAINT fk_value_form FOREIGN KEY (DailyForm_Id) REFERENCES DailyForm(DailyForm_Id) ON DELETE CASCADE,
  CONSTRAINT fk_value_item FOREIGN KEY (Item_Id) REFERENCES DailyChecklistItem(Item_Id) ON DELETE CASCADE,
  UNIQUE KEY uq_value_form_item_day (DailyForm_Id, Item_Id, Check_Day),
  INDEX idx_value_form (DailyForm_Id),
  INDEX idx_value_item (Item_Id),
  INDEX idx_value_form_item (DailyForm_Id, Item_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS Report (
  Report_Id INT NOT NULL AUTO_INCREMENT,
  Center_Id INT DEFAULT NULL,
  Machine_Id INT DEFAULT NULL,
  Details TEXT,
  Admin_Remark TEXT DEFAULT NULL,
  Photo VARCHAR(2048) DEFAULT NULL,
  Status VARCHAR(50) DEFAULT 'new',
  RPCreated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  Updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Report_Id),
  INDEX idx_report_center (Center_Id),
  INDEX idx_report_machine (Machine_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS OilLog (
  OilLog_Id INT NOT NULL AUTO_INCREMENT,
  Center_Id INT DEFAULT NULL,
  Document_No VARCHAR(50) DEFAULT NULL,
  Document_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
  Work_Order VARCHAR(100) DEFAULT NULL,
  Project_Name VARCHAR(255) DEFAULT NULL,
  Location_Name VARCHAR(255) DEFAULT NULL,
  Requester_Name VARCHAR(120) DEFAULT NULL,
  Supervisor_Name VARCHAR(120) DEFAULT NULL,
  Machine_Code VARCHAR(50) DEFAULT NULL,
  Machine_Name VARCHAR(120) DEFAULT NULL,
  Machine_Description VARCHAR(255) DEFAULT NULL,
  Operation_Details TEXT,
  Fuel_Type VARCHAR(50) NOT NULL,
  Fuel_Amount_Liters DECIMAL(10,2) NOT NULL DEFAULT 0,
  Fuel_Details_JSON JSON DEFAULT NULL,
  Photo_Attachments_JSON JSON DEFAULT NULL,
  Fuel_Ticket_No VARCHAR(80) DEFAULT NULL,
  Tank_Before_Liters DECIMAL(10,2) DEFAULT NULL,
  Tank_After_Liters DECIMAL(10,2) DEFAULT NULL,
  Meter_Hour_Start DECIMAL(10,2) DEFAULT NULL,
  Meter_Hour_End DECIMAL(10,2) DEFAULT NULL,
  Odometer_Start DECIMAL(10,2) DEFAULT NULL,
  Odometer_End DECIMAL(10,2) DEFAULT NULL,
  Work_Meter_Start DECIMAL(10,2) DEFAULT NULL,
  Work_Meter_End DECIMAL(10,2) DEFAULT NULL,
  Work_Meter_Total DECIMAL(10,2) DEFAULT NULL,
  Time_Morning_Start TIME DEFAULT NULL,
  Time_Morning_End TIME DEFAULT NULL,
  Time_Morning_Total DECIMAL(6,2) DEFAULT NULL,
  Time_Afternoon_Start TIME DEFAULT NULL,
  Time_Afternoon_End TIME DEFAULT NULL,
  Time_Afternoon_Total DECIMAL(6,2) DEFAULT NULL,
  Time_Ot_Start TIME DEFAULT NULL,
  Time_Ot_End TIME DEFAULT NULL,
  Time_Ot_Total DECIMAL(6,2) DEFAULT NULL,
  Fuel_Time TIME DEFAULT NULL,
  Operator_Name VARCHAR(120) DEFAULT NULL,
  Assistant_Name VARCHAR(120) DEFAULT NULL,
  Recorder_Name VARCHAR(120) DEFAULT NULL,
  Notes TEXT,
  Checklist_JSON TEXT DEFAULT NULL,
  Created_By VARCHAR(120) DEFAULT NULL,
  Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
  Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (OilLog_Id),
  KEY idx_oillog_center (Center_Id),
  KEY idx_oillog_document_date (Document_Date),
  KEY idx_oillog_fuel_type (Fuel_Type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MachineWorkLog (
  MachineWorkLog_Id INT NOT NULL AUTO_INCREMENT,
  Center_Id INT DEFAULT NULL,
  Document_No VARCHAR(50) DEFAULT NULL,
  Document_Date DATETIME NOT NULL,
  Project_Name VARCHAR(255) DEFAULT NULL,
  Work_Order VARCHAR(100) DEFAULT NULL,
  Work_Orders_JSON TEXT DEFAULT NULL,
  Machine_Code VARCHAR(50) DEFAULT NULL,
  Machine_Name VARCHAR(120) DEFAULT NULL,
  Machine_Description VARCHAR(255) DEFAULT NULL,
  Operation_Details TEXT DEFAULT NULL,
  Meter_Hour DECIMAL(10,2) DEFAULT NULL,
  Odometer DECIMAL(10,2) DEFAULT NULL,
  Work_Meter_Start DECIMAL(10,2) DEFAULT NULL,
  Work_Meter_End DECIMAL(10,2) DEFAULT NULL,
  Work_Meter_Total DECIMAL(10,2) DEFAULT NULL,
  Time_Morning_Start TIME DEFAULT NULL,
  Time_Morning_End TIME DEFAULT NULL,
  Time_Morning_Total DECIMAL(6,2) DEFAULT NULL,
  Time_Afternoon_Start TIME DEFAULT NULL,
  Time_Afternoon_End TIME DEFAULT NULL,
  Time_Afternoon_Total DECIMAL(6,2) DEFAULT NULL,
  Time_Ot_Start TIME DEFAULT NULL,
  Time_Ot_End TIME DEFAULT NULL,
  Time_Ot_Total DECIMAL(6,2) DEFAULT NULL,
  Checklist_JSON TEXT DEFAULT NULL,
  Created_By VARCHAR(120) DEFAULT NULL,
  Created_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated_At DATETIME DEFAULT NULL,
  PRIMARY KEY (MachineWorkLog_Id),
  KEY idx_document_date (Document_Date),
  KEY idx_machine_code (Machine_Code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS OilLogApproval (
  Approval_Id INT NOT NULL AUTO_INCREMENT,
  OilLog_Id INT NULL,
  MachineWorkLog_Id INT NULL,
  Approval_Token VARCHAR(64) NOT NULL,
  Token_Expires_At DATETIME NULL,
  Oiler_User_Id INT NULL,
  Oiler_Approved_At DATETIME NULL,
  Oiler_Remark TEXT NULL,
  Created_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Approval_Id),
  UNIQUE KEY uq_oillogapproval_token (Approval_Token),
  UNIQUE KEY uq_oillogapproval_oillog (OilLog_Id),
  UNIQUE KEY uq_oillogapproval_mwl (MachineWorkLog_Id),
  CONSTRAINT fk_oillogapproval_oillog FOREIGN KEY (OilLog_Id) REFERENCES OilLog (OilLog_Id) ON DELETE CASCADE,
  CONSTRAINT fk_oillogapproval_mwl FOREIGN KEY (MachineWorkLog_Id) REFERENCES MachineWorkLog (MachineWorkLog_Id) ON DELETE CASCADE,
  KEY idx_oillogapproval_oiler (Oiler_User_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MachineWorkLogApproval (
  Approval_Id INT NOT NULL AUTO_INCREMENT,
  MachineWorkLog_Id INT NOT NULL,
  Approval_Token VARCHAR(64) NOT NULL,
  Token_Expires_At DATETIME NULL,
  Inspector_User_Id INT NULL,
  Inspector_Approved_At DATETIME NULL,
  Inspector_Remark TEXT NULL,
  Created_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (Approval_Id),
  UNIQUE KEY uq_mwl_approval_token (Approval_Token),
  UNIQUE KEY uq_mwl_approval_log (MachineWorkLog_Id),
  CONSTRAINT fk_mwl_approval_log FOREIGN KEY (MachineWorkLog_Id) REFERENCES MachineWorkLog (MachineWorkLog_Id) ON DELETE CASCADE,
  KEY idx_mwl_approval_inspector (Inspector_User_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS=1;
